# Test170504

Qual é o valor de f após o comando f = np.zeros((100,200),dtype='uint8') ?

 f será uma lista com 100 listas onde cada uma das listas terá 200 elementos, todos do tipo uint8

 f será um ndarray com shape = (100,200) e com elementos do tipo uint8      ***

 f será um ndarray com 100 colunas e 200 linhas e com elementos do tipo uint8

 f será uma tupla com 200 tuplas onde cada uma das tuplas terá 100 elementos, todos do tipo uint8

 Nenhuma das anteriores

In [8]:
import numpy as np

f = np.zeros((100,200),dtype='uint8')
print (f)

[[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 ..., 
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]]


Qual é o valor de f.shape após o comando f = np.array([[1,2,3],[4,5,6]], 'uint8')

In [2]:
import numpy as np

f = np.array([[1,2,3],[4,5,6]], 'uint8')
print (f.shape)

(2, 3)


Quais são os 3 tipos de cópias de ndarrays?

rasa, profunda e sem cópia

Seja f um ndarray com shape (100,200). O que podemos dizer do comando f[:10,20:] = 0 ?

`:10` = start to 10 

`20:` = 20 to end

Irá zerar as últimas 180 colunas das 10 primeiras linhas da imagem f

In [14]:
import numpy as np

f = np.ones((100,200),dtype='uint8')
print (f)
f[:10,20:] = 0
print ("f[:10,20:] = 0")
print (f, "\n")

f = np.ones((10,20),dtype='uint8')
print (f)
f[:1,2:] = 0
print ("f[:1,2:] = 0")
print (f, "\n")

f = np.ones((10,20),dtype='uint8')
print (f)
f[:7,8:] = 0
print ("f[:7,8:] = 0")
print (f, "\n")

[[1 1 1 ..., 1 1 1]
 [1 1 1 ..., 1 1 1]
 [1 1 1 ..., 1 1 1]
 ..., 
 [1 1 1 ..., 1 1 1]
 [1 1 1 ..., 1 1 1]
 [1 1 1 ..., 1 1 1]]
f[:10,20:] = 0
[[1 1 1 ..., 0 0 0]
 [1 1 1 ..., 0 0 0]
 [1 1 1 ..., 0 0 0]
 ..., 
 [1 1 1 ..., 1 1 1]
 [1 1 1 ..., 1 1 1]
 [1 1 1 ..., 1 1 1]] 

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
f[:1,2:] = 0
[[1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1

Seja o shape da imagem f.shape igual a (H,W) com dtype='uint8'. O que faz o comando f[H/2,:] = 255 ?

Traça uma linha horizontal no meio da imagem

In [26]:
import numpy as np

f = np.arange(200) # a é um vetor unidimensional de 20 elementos
f = f.reshape(10,20) # a agora é um array 4x5 (4 linhas por 5 colunas)

H = f.shape[0]
print (H)

f[5,:] = 255

print ("f[H/2,:] = 255")
print (f, "\n")


%timeit a = np.zeros((1000000,))

10
f[H/2,:] = 255
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
   38  39]
 [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
   58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
  255 255]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
  138 139]
 [140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
  158 159]
 [160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177
  178 179]
 [180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
  198 199]] 

